--
-- PostgreSQL database dump
--

\restrict dHRyjNFV6RsKx8a2BwXBB3A8aReBu9wDKlHn5cmIUyezaTeQoaoIYyQ7fnTUTQB

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    label text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: categories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.categories_id_seq OWNED BY public.categories.id;


--
-- Name: clubs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clubs (
    id bigint NOT NULL,
    name text NOT NULL,
    city text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: clubs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.clubs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: clubs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.clubs_id_seq OWNED BY public.clubs.id;


--
-- Name: competitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.competitions (
    id bigint NOT NULL,
    name text NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    price numeric(10,2) DEFAULT 0 NOT NULL,
    sup_category_price numeric(10,2) DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: competitions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.competitions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: competitions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.competitions_id_seq OWNED BY public.competitions.id;


--
-- Name: distances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.distances (
    id bigint NOT NULL,
    label text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: distances_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.distances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: distances_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.distances_id_seq OWNED BY public.distances.id;


--
-- Name: para_classifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.para_classifications (
    id bigint NOT NULL,
    label text NOT NULL,
    value text,
    sort_order integer DEFAULT 0 NOT NULL
);


--
-- Name: para_classifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.para_classifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.para_classifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shooters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shooters (
    id bigint NOT NULL,
    last_name text NOT NULL,
    first_name text NOT NULL,
    email text,
    club_id bigint NOT NULL,
    competition_id bigint NOT NULL,
    distance_id bigint NOT NULL,
    weapon_id bigint NOT NULL,
    category_id bigint NOT NULL,
    serie1_score numeric(5,2),
    serie2_score numeric(5,2),
    serie3_score numeric(5,2),
    serie4_score numeric(5,2),
    serie5_score numeric(5,2),
    serie6_score numeric(5,2),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL,
    serie7_score numeric,
    serie8_score numeric,
    para_classification text
);


--
-- Name: shooters_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.shooters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: shooters_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.shooters_id_seq OWNED BY public.shooters.id;


--
-- Name: weapons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.weapons (
    id bigint NOT NULL,
    label text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: weapons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.weapons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: weapons_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.weapons_id_seq OWNED BY public.weapons.id;


--
-- Name: categories id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories ALTER COLUMN id SET DEFAULT nextval('public.categories_id_seq'::regclass);


--
-- Name: clubs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clubs ALTER COLUMN id SET DEFAULT nextval('public.clubs_id_seq'::regclass);


--
-- Name: competitions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.competitions ALTER COLUMN id SET DEFAULT nextval('public.competitions_id_seq'::regclass);


--
-- Name: distances id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.distances ALTER COLUMN id SET DEFAULT nextval('public.distances_id_seq'::regclass);


--
-- Name: shooters id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shooters ALTER COLUMN id SET DEFAULT nextval('public.shooters_id_seq'::regclass);


--
-- Name: weapons id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weapons ALTER COLUMN id SET DEFAULT nextval('public.weapons_id_seq'::regclass);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: clubs clubs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clubs
    ADD CONSTRAINT clubs_pkey PRIMARY KEY (id);


--
-- Name: competitions competitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.competitions
    ADD CONSTRAINT competitions_pkey PRIMARY KEY (id);


--
-- Name: distances distances_label_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.distances
    ADD CONSTRAINT distances_label_key UNIQUE (label);


--
-- Name: distances distances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.distances
    ADD CONSTRAINT distances_pkey PRIMARY KEY (id);


--
-- Name: para_classifications para_classifications_label_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.para_classifications
    ADD CONSTRAINT para_classifications_label_key UNIQUE (label);


--
-- Name: para_classifications para_classifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.para_classifications
    ADD CONSTRAINT para_classifications_pkey PRIMARY KEY (id);


--
-- Name: para_classifications para_classifications_value_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.para_classifications
    ADD CONSTRAINT para_classifications_value_key UNIQUE (value);


--
-- Name: shooters shooters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shooters
    ADD CONSTRAINT shooters_pkey PRIMARY KEY (id);


--
-- Name: weapons weapons_label_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weapons
    ADD CONSTRAINT weapons_label_key UNIQUE (label);


--
-- Name: weapons weapons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weapons
    ADD CONSTRAINT weapons_pkey PRIMARY KEY (id);


--
-- Name: shooters shooters_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shooters
    ADD CONSTRAINT shooters_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE RESTRICT;


--
-- Name: shooters shooters_club_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shooters
    ADD CONSTRAINT shooters_club_id_fkey FOREIGN KEY (club_id) REFERENCES public.clubs(id) ON DELETE CASCADE;


--
-- Name: shooters shooters_competition_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shooters
    ADD CONSTRAINT shooters_competition_id_fkey FOREIGN KEY (competition_id) REFERENCES public.competitions(id) ON DELETE CASCADE;


--
-- Name: shooters shooters_distance_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shooters
    ADD CONSTRAINT shooters_distance_id_fkey FOREIGN KEY (distance_id) REFERENCES public.distances(id) ON DELETE RESTRICT;


--
-- Name: shooters shooters_weapon_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shooters
    ADD CONSTRAINT shooters_weapon_id_fkey FOREIGN KEY (weapon_id) REFERENCES public.weapons(id) ON DELETE RESTRICT;


--
-- Name: para_classifications Allow read para classifications; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow read para classifications" ON public.para_classifications FOR SELECT TO authenticated, anon USING (true);


--
-- Name: categories Allow select on categories; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow select on categories" ON public.categories FOR SELECT USING (true);


--
-- Name: distances Allow select on distances; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow select on distances" ON public.distances FOR SELECT USING (true);


--
-- Name: weapons Allow select on weapons; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow select on weapons" ON public.weapons FOR SELECT USING (true);


--
-- Name: clubs Club: insert own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Club: insert own" ON public.clubs FOR INSERT WITH CHECK ((user_id = auth.uid()));


--
-- Name: clubs Club: select own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Club: select own" ON public.clubs FOR SELECT USING ((user_id = auth.uid()));


--
-- Name: clubs Club: update own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Club: update own" ON public.clubs FOR UPDATE USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));


--
-- Name: competitions Competition: insert own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Competition: insert own" ON public.competitions FOR INSERT WITH CHECK ((user_id = auth.uid()));


--
-- Name: competitions Competition: select own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Competition: select own" ON public.competitions FOR SELECT USING ((user_id = auth.uid()));


--
-- Name: competitions Competition: update own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Competition: update own" ON public.competitions FOR UPDATE USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));


--
-- Name: shooters Shooter: insert own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Shooter: insert own" ON public.shooters FOR INSERT TO authenticated WITH CHECK (((user_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM public.clubs
  WHERE ((clubs.id = shooters.club_id) AND (clubs.user_id = auth.uid())))) AND (EXISTS ( SELECT 1
   FROM public.competitions
  WHERE ((competitions.id = shooters.competition_id) AND (competitions.user_id = auth.uid()))))));


--
-- Name: shooters Shooter: select own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Shooter: select own" ON public.shooters FOR SELECT USING ((user_id = auth.uid()));


--
-- Name: shooters Shooter: update own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Shooter: update own" ON public.shooters FOR UPDATE TO authenticated USING ((user_id = auth.uid())) WITH CHECK (((user_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM public.clubs
  WHERE ((clubs.id = shooters.club_id) AND (clubs.user_id = auth.uid())))) AND (EXISTS ( SELECT 1
   FROM public.competitions
  WHERE ((competitions.id = shooters.competition_id) AND (competitions.user_id = auth.uid()))))));


--
-- Name: categories; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

--
-- Name: clubs; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.clubs ENABLE ROW LEVEL SECURITY;

--
-- Name: competitions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.competitions ENABLE ROW LEVEL SECURITY;

--
-- Name: clubs delete own clubs; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "delete own clubs" ON public.clubs FOR DELETE TO authenticated USING ((user_id = auth.uid()));


--
-- Name: competitions delete own competitions; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "delete own competitions" ON public.competitions FOR DELETE TO authenticated USING ((user_id = auth.uid()));


--
-- Name: shooters delete own shooters; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "delete own shooters" ON public.shooters FOR DELETE TO authenticated USING ((user_id = auth.uid()));


--
-- Name: distances; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.distances ENABLE ROW LEVEL SECURITY;

--
-- Name: para_classifications; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.para_classifications ENABLE ROW LEVEL SECURITY;

--
-- Name: shooters; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.shooters ENABLE ROW LEVEL SECURITY;

--
-- Name: weapons; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.weapons ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

\unrestrict dHRyjNFV6RsKx8a2BwXBB3A8aReBu9wDKlHn5cmIUyezaTeQoaoIYyQ7fnTUTQB

