/**
 * Noms d'icônes Iconify
 */
export const APP_ICONS = {
	COMPETITION: 'octicon:trophy-24',
	CLUB: 'lucide:shield',
	REPORTS: 'mdi:paper-outline',
	EDIT: 'lucide:pen-line',
	DELETE: 'formkit:trash',
	ADD: 'lucide:plus-circle',
	DOWNLOAD: 'material-symbols:download-rounded',
	DISPLAY: 'streamline:screen-1-remix',
	USER: 'lucide:user-round',
	EMAIL_SEND: 'mdi:email-send',
	PASSWORD_RESET: 'mdi:password-reset',
	DISCONNECT: 'fluent:plug-disconnected-24-filled',
	EYE: 'mynaui:eye',
	EYE_SLASH: 'mynaui:eye-slash',
	ARROW_RIGHT: 'tabler:arrow-right',
	LOADING: 'line-md:loading-loop',
	INFO: 'lucide:info',
	HELP: 'lucide:help-circle',
	SETTINGS: 'majesticons:settings-cog-line',
	SPARKLES: 'lucide:sparkles',
	MONITOR: 'lucide:monitor',
	MINIMIZE: 'lucide:minimize-2',
	MAXIMIZE: 'lucide:maximize-2',
	SEND: 'tabler:send',
	ARROW_LEFT: 'tabler:arrow-left',
	PLAY: 'heroicons:play',
	ALERT: 'lucide:alert-triangle',
	CHECK: 'mdi:check',
	CLOSE: 'mdi:close',
} as const;
